# Generated by Django 5.0.7 on 2025-01-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='barber',
            field=models.CharField(default='Cualquiera', max_length=100),
        ),
    ]
